const Reports = {
    async generateMonthlyReport() {
        // Dynamic Import or assume loaded in HTML
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        const date = new Date();
        const monthName = date.toLocaleString('default', { month: 'long', year: 'numeric' });

        // Header
        doc.setFontSize(22);
        doc.setTextColor(99, 102, 241); // Indigo
        doc.text("INFI X TECH", 14, 20);

        doc.setFontSize(14);
        doc.setTextColor(100);
        doc.text(`Monthly Report - ${monthName}`, 14, 30);

        // Load Data
        const stats = await Firestore.getDashboardStats();

        // Summary Table
        doc.autoTable({
            startY: 40,
            head: [['Metric', 'Value']],
            body: [
                ['Active Members', stats.activeMembers],
                ['Tasks Completed', `${stats.completed}/${stats.total}`],
                ['Events Active', stats.activeEvents],
                // ['Club Balance', Utils.formatCurrency(stats.balance)] // Currency char might break PDF without font, use "Rs."
                ['Club Balance', `Rs. ${stats.balance}`]
            ],
            theme: 'grid',
            headStyles: { fillColor: [99, 102, 241] }
        });

        // Transactions (Fetch from generic if needed, here just summary)
        doc.text("Generated by Log Portal", 14, doc.internal.pageSize.height - 10);

        doc.save(`Report_${monthName}.pdf`);
    }
};

window.Reports = Reports;
